### ISSUE TITLE
 cannot import name 'platform_ndk_pb2' from 'platform_ndk'

### ISSUE THREAD

**Issue by ranjekum** [nokia/sonic-platform#2]
ImportError: cannot import name 'platform_ndk_pb2' from 'platform_ndk' (/usr/local/lib/python3.7/dist-packages/platform_ndk/__init__.py)
> /usr/local/lib/python3.7/dist-packages/platform_ndk/nokia_common.py(16)<module>()
-> from platform_ndk import platform_ndk_pb2

There is no module named 'platform_ndk_pb2' inside sonic-platform main branch.

**Comment by mlok-nokia** [comment]
No longer a issue
